console.log("Hey there! Did u find me by following the instructions? If yes then Great Job!");
var sportnamefoot= "Foot";
console.log(sportnamefoot);
var sportnameball= "ball";
console.log(sportnameball);
var sportnamefull=sportnamefoot.concat(sportnameball);
console.log(sportnamefull);
var a= 3;
console.log(a);
var b= 5;
console.log(b);
var c= 9;
console.log(c);
var d= 7;
console.log(d);
var e= 11;
console.log(e);
var operation= e+d-c/b*a;
console.log(operation);
